### ISSUE TITLE
AttributeError: '_AutomationClient' object has no attribute 'dll' 

### ISSUE THREAD

**Issue by vijaysaimutyala** [yinkaisheng/Python-UIAutomation-for-Windows#22]
Hi,

I am trying to set the module on Windows 10. I am running a python script to open the Notepad and with admin rights, but i received the below log. Am I missing something that needs to be done with the DLL files of the library?

 AutomationClientX86.dll 
AutomationClientX64.dll

Are these files already present or should be manually included in the system path?
```
Traceback (most recent call last):
  File "automate.py", line 2, in <module>
    import uiautomation as automation
  File "C:\Users\anant.pande\AppData\Roaming\Python\Python35\site-packages\uiautomation.py", line 55, in <module>
    _automationClient = _AutomationClient()
  File "C:\Users\anant.pande\AppData\Roaming\Python\Python35\site-packages\uiautomation.py", line 45, in __init__
    self.dll = ctypes.cdll.UIAutomationClientX64
  File "<C:\Program Files\Anaconda3\lib\ctypes\__init__.py>", line 417, in __getattr__
    dll = self._dlltype(name)
  File "<C:\Program Files\Anaconda3\lib\ctypes\__init__.py>", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Exception ignored in: <bound method _AutomationClient.__del__ of <uiautomation._AutomationClient object at 0x000002BF64E952E8>>
Traceback (most recent call last):
  File "C:\Users\anant.pande\AppData\Roaming\Python\Python35\site-packages\uiautomation.py", line 52, in __del__
    self.dll.ReleaseInstance()
AttributeError: '_AutomationClient' object has no attribute 'dll' 
```

**Comment by yinkaisheng** [comment]
Do the two dlls exist in you dir C:\Users\anant.pande\AppData\Roaming\Python\Python35\site-packages?

**Comment by vijaysaimutyala** [comment]
Yes they do. Need to point out one more thing. This is a  Windows 10 machine. I was able to successfully set this up on a Windows 7 machine. I've admin privileges on both the machines

**Comment by yinkaisheng** [comment]
Python 3.5 and 3.6 were built by VS2015.
My dlls were build by VS2010. The dlls can't be run if your OS doesn't have VS2010 dependence.
I have recompiled the dlls to fit different python versions.
Update uiautomation by 'pip install -U uiautomation' and try again.

**Comment by vijaysaimutyala** [comment]
I'll check this and let u know.

**Comment by yinkaisheng** [comment]
What's the result?

**Comment by vijaysaimutyala** [comment]
Sorry for the delay. Was caught up with work. Just checked it on a new Windows 10 machine. I'm running into access issues as in #17 .

Tried updating the UIAutomation without any luck.

One more issue I've observed is that, I've defined a method A to take control of a window in script automate.py. Now when I make a call to this method A from a different script, the script is able to open the subprocess but unable to get the window handle and fails with a timeout error. Will post the log on Monday.

**Comment by yinkaisheng** [comment]
Please update the code and test again. I fixed the issue with 64 bit Python.
It should work now.

**Comment by vijaysaimutyala** [comment]
I update the library and I still see the same issue.


![capture](https://user-images.githubusercontent.com/7084628/28255423-51a03542-6ad4-11e7-8f12-cf255aadc583.PNG)

**Comment by vijaysaimutyala** [comment]
I was able to fix this on one Windows 10 PC. Still have an issue with other PC. Will check and update here.

**Comment by yinkaisheng** [comment]
I only have one PC. I can't reproduce the bug on my Windows 10 PC.
Install [Visual C++ Redistributable for Visual Studio 2015 64 Bit](https://www.microsoft.com/zh-cn/download/details.aspx?id=48145) and try again.

**Comment by yinkaisheng** [comment]
Latest uiautomation 2.0 can be run without dlls.

**Comment by DaniloToroL** [comment]
I have the same error. I am building a tracker and I am getting the object while moving the mouse. Everything is fine when starting but after about 5 seconds it fails, I have not been able to know what happens. Does the DLL crash when trying so many times in a row?

This is the complete error:

```
Exception ignored in: <bound method _DllClient.__del__ of <uiautomation.uiautomation._DllClient object at 0x06598510>>
Traceback (most recent call last):
  File "C:\Users\danil\dev\recorder\desktop\.env\lib\site-packages\uiautomation\uiautomation.py", line 133, in __del__
    if self.dll:
AttributeError: '_DllClient' object has no attribute 'dll'

```

**Comment by Unknowncabbage** [comment]
> 我有同样的错误。我正在构建一个跟踪器，并在移动鼠标时获取对象。启动时一切正常，但大约 5 秒后它失败了，我一直不知道会发生什么。连续尝试这么多次时 DLL 会崩溃吗？
> 
> 这是完整的错误：
> 
> ```
> Exception ignored in: <bound method _DllClient.__del__ of <uiautomation.uiautomation._DllClient object at 0x06598510>>
> Traceback (most recent call last):
>   File "C:\Users\danil\dev\recorder\desktop\.env\lib\site-packages\uiautomation\uiautomation.py", line 133, in __del__
>     if self.dll:
> AttributeError: '_DllClient' object has no attribute 'dll'
> ```

Dude, did you solve the problem?
